from pages.product.product_help_main_page import ProductHelpMainPage

class TestHelpMainPage():

    def test_help_pege(self, browser):
        product_page = ProductHelpMainPage(browser, 'https://www.combin.com/help/')
        product_page.open()
        product_page.cookies_close()
        product_page.help_main_heading()
        product_page.help_main_text()
        product_page.navigation_faq()
        product_page.navigation_guides()
        product_page.navigation_howto()
        product_page.navigation_troubleshooting()

# Section Essential
        product_page.essential()
        product_page.getting_started_to_grow()
        product_page.getting_started_to_grow_text()
        product_page.getting_started_to_grow_symbol()
        product_page.getting_started_to_plan()
        product_page.getting_started_to_plan_text()
        product_page.getting_starter_to_plan_symbol()
        product_page.is_combin_safe()
        product_page.is_combin_safe_text()
        product_page.is_combin_safe_symbol()

# Section Search
        product_page.search()
        product_page.how_do_i_get_more()
        product_page.how_do_i_get_more_text()
        product_page.how_do_i_get_more_symbol()
        product_page.what_are_sorting()
        product_page.what_are_sorting_text()
        product_page.what_are_sorting_symbol()
        product_page.how_to_use_advanced()
        product_page.how_to_use_advanced_text()
        product_page.how_to_use_advanced_symbol()

#Section User
        product_page.user()
        product_page.how_to_add_instagram()
        product_page.how_to_add_instagram_text()
        product_page.how_to_add_instagram_symbol()
        product_page.how_to_add_users_to_blacklict()
        product_page.how_to_add_users_to_blacklist_text()
        product_page.how_to_add_users_to_blacklist_symbol()
        product_page.how_to_backup_combin()
        product_page.how_to_backup_combin_text()
        product_page.how_to_backup_combin_symbol()
        product_page.where_to_find_unfollowers()
        product_page.where_to_find_unfollowers_text()
        product_page.where_to_find_unfollowers_symbol()
        product_page.how_to_export_users()
        product_page.how_to_export_users_text()
        product_page.how_to_export_users_symbol()

#Section Login
        product_page.login()
        product_page.how_to_login_account()
        product_page.how_to_login_account_text()
        product_page.how_to_login_account_symbol()
        product_page.how_to_logout()
        product_page.how_to_logout_text()
        product_page.how_to_logout_symbol()
        product_page.how_to_find_the_application()
        product_page.how_to_find_the_application_text()
        product_page.how_to_find_the_application_symbol()

#Section General
        product_page.general()
        product_page.application_keyboard()
        product_page.application_keyboard_text()
        product_page.application_keyboard_symbol()
        product_page.application_icons()
        product_page.application_icon_text()
        product_page.application_icon_symbol()

#Section HowTo

        product_page.howto()
        product_page.howto_unfollowings_instagram_users()
        product_page.howto_unfollowings_instagram_users_text()
        product_page.howto_unfollowings_instagram_users_symbol()
        product_page.howto_find_and_engage()
        product_page.howto_find_and_engage_text()
        product_page.howto_find_and_engage_symbol()
        product_page.howto_distinguish_real_followers()
        product_page.howto_distinguish_real_followers_text()
        product_page.howto_distinguish_real_followers_symbol()
        product_page.howto_find_your_target_audience()
        product_page.howto_find_your_target_audience_text()
        product_page.howto_find_your_target_audience_symbol()
        product_page.howto_find_influencers()
        product_page.howto_find_influencers_text()
        product_page.howto_find_influencers_symbol()
        product_page.howto_interact()
        product_page.howto_interact_text()
        product_page.howto_interact_symbol()
        product_page.howto_safely()
        product_page.howto_safely_text()
        product_page.howto_safely_symbol()
        product_page.howto_leave_multiple_instagram()
        product_page.howto_leave_multiple_instagram_text()
        product_page.howto_leave_multiple_instagram_symbol()
        product_page.howto_automate_instagram_activity()
        product_page.howto_automate_instagram_activity_text()
        product_page.howto_automate_instagram_activity_symbol()
        product_page.howto_get_instagram_account()
        product_page.howto_get_instagram_account_text()
        product_page.howto_get_instagram_account_symbol()
        product_page.howto_setup_instagram_hashtags()
        product_page.howto_setup_instagram_hashtags_text()
        product_page.howto_setup_instagram_hashtags_symbol()
        product_page.howto_sort_and_filter_search()
        product_page.howto_sort_and_filter_search_text()
        product_page.howto_sort_and_filter_search_symbol()
        product_page.howto_use_advanced_filters()
        product_page.howto_use_advanced_filters_text()
        product_page.howto_use_advanced_filters_symbol()
        product_page.howto_scheduler_instagram_posts()
        product_page.howto_scheduler_instagram_posts_text()
        product_page.howto_scheduler_instagram_posts_symbol()
        product_page.howto_scheduler_instagram_stories()
        product_page.howto_scheduler_instagram_stories_text()
        product_page.howto_scheduler_instagram_stories_symbol()
        product_page.howto_repost_instagram()
        product_page.howto_repost_instagram_text()
        product_page.howto_repost_instagram_symbol()


#Section FAQ

        product_page.faq()
        product_page.will_grow()
        product_page.will_grow_text()
        product_page.will_grow_symbol()
        product_page.what_are_action_limits()
        product_page.what_are_action_limits_text()
        product_page.what_are_action_limits_symbol()
        product_page.does_combin_support()
        product_page.does_combin_support_text()
        product_page.does_combin_support_symbol()
        product_page.what_is_safe_list()
        product_page.what_is_safe_list_text()
        product_page.what_is_safe_list_symbol()
        product_page.what_are_the_hardware()
        product_page.what_are_the_hardware_text()
        product_page.what_are_the_hardware_symbol()
        product_page.does_it_work()
        product_page.does_it_work_text()
        product_page.does_it_work_symbol()
        product_page.what_are_the_irrelevant()
        product_page.what_are_the_irrelevant_text()
        product_page.what_are_the_irrelevant_symbol()
        product_page.where_to_find_proxy()
        product_page.where_to_find_proxy_text()
        product_page.where_to_find_proxy_symbol()
        product_page.where_do_i_get_starter_plan()
        product_page.where_do_i_get_starter_plan_text()
        product_page.where_do_i_get_starter_plan_symbol()

#Section Troubleshooting

        product_page.troubleshooting()
        product_page.commenting_task_stuck()
        product_page.commenting_task_stuck_text()
        product_page.commenting_task_stuck_symbol()
        product_page.profile_and_users()
        product_page.profile_and_users_text()
        product_page.profile_and_users_symbol()
        product_page.search_results()
        product_page.search_results_text()
        product_page.search_results_symbol()
        product_page.the_application_loading()
        product_page.the_application_loading_text()
        product_page.the_application_loading_symbol()
        product_page.the_application_returns()
        product_page.the_application_returns_text()
        product_page.the_application_returns_symbol()
        product_page.action_task_spending()
        product_page.action_task_spending_text()
        product_page.action_task_spending_symbol()
        product_page.two_factor_authentication_code()
        product_page.two_factor_authentication_code_text()
        product_page.two_factor_authentication_code_symbol()
        product_page.why_do_i_see_waiting_for_instagram_callback()
        product_page.why_do_i_see_waiting_for_instagram_callback_text()
        product_page.why_do_i_see_waiting_for_instagram_callback_symbol()
        product_page.why_di_i_see_following_limit_reached()
        product_page.why_di_i_see_following_limit_reached_text()
        product_page.why_di_i_see_following_limit_reached_symbol()
        product_page.why_are_not_action_processed()
        product_page.why_are_not_action_processed_text()
        product_page.why_are_not_action_processed_symbol()